### PR TITLE
enable sourcelink support

### PR DESCRIPTION
**Pull request by ctaggart**
I built it on my own appveyor and tested the resulting nupkg:

```
PS C:\Users\taggac\github\helm> sourcelink test "C:\Users\taggac\Downloads\Helm.0.1.28-g6e0319b02d\lib\netstandard2.0\Helm.pdb"
sourcelink test passed: C:\Users\taggac\Downloads\Helm.0.1.28-g6e0319b02d\lib\netstandard2.0\Helm.pdb
PS C:\Users\taggac\github\helm> sourcelink print-documents "C:\Users\taggac\Downloads\Helm.0.1.28-g6e0319b02d\lib\netstandard2.0\Helm.pdb"
d8907519e9aa4a72074bab72a7ec01b6d2d7fa68 sha1 csharp C:\projects\helm\src\Helm\Hapi\Version.cs
709bb23f9b8384f861578696b1d18e503821ac18 sha1 csharp C:\projects\helm\src\Helm\Hapi\Tiller.cs
8862bbe9da423b8353ebe7686dc934fc387ffa7c sha1 csharp C:\projects\helm\src\Helm\Hapi\TillerGrpc.cs
6a924e8122f87d7c6de9a5fa85fe7ef35dc39eec sha1 csharp C:\projects\helm\src\Helm\Hapi\Rudder.cs
a053f21620707cb98f0ace873c26957438069600 sha1 csharp C:\projects\helm\src\Helm\Hapi\RudderGrpc.cs
e0c60007b9ab576131ae9d3d83ed2dbc2e36f3fd sha1 csharp C:\projects\helm\src\Helm\Hapi\Hook.cs
85582308c68406e67a47c510c8e5a2d52e2d128f sha1 csharp C:\projects\helm\src\Helm\Hapi\Info.cs
b0dbe13bc5d937d82dad3f68311f3295becd96af sha1 csharp C:\projects\helm\src\Helm\Hapi\Release.cs
e9d85e45d41d19ce4ef4998fb13bbda4448f39f3 sha1 csharp C:\projects\helm\src\Helm\Hapi\Status.cs
9d12dbb2613dd4d6c5217bd948a5f4a045b73abd sha1 csharp C:\projects\helm\src\Helm\Hapi\TestRun.cs
a7c060d213494c68a98e0e6dc9ea30f32c964e28 sha1 csharp C:\projects\helm\src\Helm\Hapi\TestSuite.cs
0ef8d8f023abab76301e92356229e10929847ff5 sha1 csharp C:\projects\helm\src\Helm\Hapi\Chart.cs
9071a15363298aa5fc712b7d0d3810815a99c8e5 sha1 csharp C:\projects\helm\src\Helm\Hapi\Config.cs
979a86e27319409105521f2826d811747e756dff sha1 csharp C:\projects\helm\src\Helm\Hapi\Metadata.cs
8876ac0e90c9d7e11ddbef5572888faabd057a50 sha1 csharp C:\projects\helm\src\Helm\Hapi\Template.cs
c881c2fa1344c81d6a19310571a2957b4a0756c0 sha1 csharp C:\projects\helm\src\Helm\Helm\AsyncStreamReader.cs
7bb47839cbbfdce0c78cf674c42853ffae663b90 sha1 csharp C:\projects\helm\src\Helm\Helm\StreamCallInvoker.cs
e9228d647b1113a41395471ffd17b53f59cf0ab2 sha1 csharp C:\projects\helm\src\Helm\Helm\TillerClient.cs
8ae96ae9a4e73c48a6d957767420f85e2c3ec4b3 sha1 csharp C:\projects\helm\src\Helm\Helm\TillerLocator.cs
b376e599ab7fcf263ea344eb0fc01452f9aff6d2 sha1 csharp C:\projects\helm\src\Helm\Helm\TillerNotFoundException.cs
19ea5420567ebb2188481a9b21c8ca12e4bf2fa2 sha1 csharp C:\projects\helm\src\Helm\Charts\ChartPackage.cs
ab2fde4515d237bda0402bc0beab50e70ca056ae sha1 csharp C:\projects\helm\src\Helm\Charts\ChartPackageBuilder.cs
```

### CODE REVIEW

**Comment by qmfrederik** [comment]
Thank you for doing this!

If Travis is giving you trouble - .NET Core is installed manually during the Travis CI run; see `ci/install.sh`.

**Comment by qmfrederik** [comment]
@ctaggart You'll probably have to rebase this on the master now that #13 came through. It's evening in my time zone, but assuming the build passes I should be able to get this merged tomorrow.

**Comment by ctaggart** [comment]
No rebase needed. Assuming it builds, just **squash** merge it.

**Comment by qmfrederik** [comment]
Yeah, merging master should also work ;-)

**Comment by ctaggart** [comment]
Something seems flaky about the `Helm.IntegrationTests`

**Comment by qmfrederik** [comment]
Yes, though it doesn't seem to be related to this change. (Looks like the flakiness started after an upgrade to a newer version of the KubernetesClient).

**Pull request merged**
